resources:
  - cert-manager.resources.yaml
  - k8ssandra-operator.resources.yaml
  - kube-prometheus.resources.yaml
  - demo.k8ssandracluster.yaml
  - demo.servicemonitor.yaml
  - k8ssandra-dashboards.configmap.yaml
patches:
  - path: grafana.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: grafana
