apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: pd-ssd.yaml
    target:
      group: k8ssandra.io
      version: v1alpha1
      kind: K8ssandraCluster
      name: demo