apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: "3.11.7"
  managementApiAuth:
    insecure: {}
  size: 3
  racks:
    - name: rack1
      nodeAffinityLabels:
        topology.kubernetes.io/zone: us-central1-a
    - name: rack2
      nodeAffinityLabels:
        topology.kubernetes.io/zone: us-central1-b
    - name: rack3
      nodeAffinityLabels:
        topology.kubernetes.io/zone: us-central1-c
  resources:
    requests:
      memory: 20Gi
      cpu: 3000m
    limits:
      memory: 20Gi
      cpu: 3000m
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: standard-rwo
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1024Gi
  stopped: false
  config:    
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: "8G"
      max_heap_size: "8G"
      additional-jvm-opts:
        # As the database comes up for the first time, set system keyspaces to RF=3
        - "-Ddse.system_distributed_replication_dc_names=dc1"
        - "-Ddse.system_distributed_replication_per_dc=1"
